# Generated by Django 3.2.7 on 2022-03-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(max_length=32, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=32, verbose_name='菜单名称'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(default=1, max_length=32, unique=True, verbose_name='URL别名'),
            preserve_default=False,
        ),
    ]
